# Generated by Django 6.0.1 on 2026-01-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('swagger_url', models.URLField(help_text='URL del file JSON/YAML della documentazione OpenAPI')),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
