# Generated by Django 6.0.1 on 2026-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetapi',
            name='last_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
