# Generated by Django 6.0.1 on 2026-01-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_targetapi_last_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetapi',
            name='last_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetapi',
            name='swagger_url',
            field=models.URLField(),
        ),
    ]
