# Generated by Django 6.0.1 on 2026-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_targetapi_last_analysis_alter_targetapi_swagger_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetapi',
            name='is_auto_active',
            field=models.BooleanField(default=True),
        ),
    ]
